version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.13.0
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.13.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=elastic-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local
